package repository

import "github.com/crossplane/upjet/pkg/config"

// Configure configures individual resources by adding custom ResourceConfigurators.
func Configure(p *config.Provider) {
    p.AddResourceConfigurator("bitbucket_repository", func(r *config.Resource) {
        // Override the default group generated by upjet, if necessary
        r.ShortGroup = "repository"
    })
}
